name: dragon-chat
version: 2.3.82
summary: Dragon Chat Desktop Client for Linux
description: Dragon Chat combines the immediacy of Slack with an email threading model. With Dragon Chat, you can catch up on important conversations while ignoring irrelevant ones.
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  dragon-chat:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/dragon-chat
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: dist/linux-unpacked
    after:
      - desktop-gtk3
